name = "hypercog"
compatibility_date = "2024-12-16"

# Configure build output directory for Pages
pages_build_output_dir = "build"

# KV Storage for persistence
[[kv_namespaces]]
binding = "HYPERCOG_KV"
id = "d1fcd8dbbd35aec43e5499200f6baede"

# Queue for processing improvements
[[queues.producers]]
binding = "IMPROVEMENT_QUEUE" 
queue = "improvement-tasks"

[[queues.consumers]]
queue = "improvement-tasks"
max_batch_size = 10
max_batch_timeout = 30

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "hypercog"
database_id = "d1fcd8dbbd35aec43e5499200f6baede"