import type { ImprovementAction } from '../../types';

export function generatePRDescription(improvement: ImprovementAction): string {
  return `
# ${improvement.description}

## Type: ${improvement.type}
## Priority: ${improvement.priority}
## Estimated Impact: ${improvement.estimatedImpact}

## Changes:
${improvement.changes.map(c => `- ${c.path}`).join('\n')}

Generated by HyperCog Self-Improvement System
  `.trim();
}