name = "cron"
main = "src/index.ts"
compatibility_date = "2024-12-16"

# KV Storage for persistence
[[kv_namespaces]]
binding = "HYPERCOG_KV"
id = "d1fcd8dbbd35aec43e5499200f6baede"

# Queue for processing improvements
[[queues.producers]]
binding = "IMPROVEMENT_QUEUE" 
queue = "improvement-tasks"

[[queues.consumers]]
queue = "improvement-tasks"
max_batch_size = 10
max_batch_timeout = 30

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "hypercog"
database_id = "d1fcd8dbbd35aec43e5499200f6baede"

# Environment variables
[vars]
TRIGGER_DEV = "tr_dev_fhewICDhovjy5zZgScHy"
TRIGGER_PAT = "tr_pat_7u67tbpefhp668f4tn5oy4a4rfjv4jagibd9yap4"
GIT_HUB_API_KEY = "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"
GIT_HUB_REPO_URL = "https://github.com/EchoCog/hypercog"