export const IMPROVEMENT_THRESHOLDS = {
  MEMORY: {
    MAX_HEAP_USAGE_INCREASE: 0.1,
    MIN_HEAP_USAGE_DECREASE: 0.05
  },
  PERFORMANCE: {
    MAX_RESPONSE_TIME_INCREASE: 0.1,
    MIN_RESPONSE_TIME_DECREASE: 0.05,
    MAX_ERROR_RATE_INCREASE: 0.01,
    MIN_ERROR_RATE_DECREASE: 0.005,
    MAX_THROUGHPUT_DECREASE: 0.1,
    MIN_THROUGHPUT_INCREASE: 0.05
  }
} as const;